#include "workflow-trigger-filter-ui.h"
#include "workflow-model.h"
#include "workflow-persistence.h"
#include <obs.h>

namespace {
static void fill_triggers(obs_property_t *p,const workflow_t*w){obs_property_list_clear(p);if(!w){obs_property_list_add_string(p,"Select a workflow first","");return;}for(size_t i=0;i<w->node_count;++i)if(w->nodes[i].type==WORKFLOW_NODE_TRIGGER)obs_property_list_add_string(p,w->nodes[i].name,w->nodes[i].id);}
static bool workflow_modified(obs_properties_t*props,obs_property_t*,obs_data_t*s){auto*m=workflow_persistence_manager();auto*w=m?workflow_manager_find(m,obs_data_get_string(s,"workflow")):nullptr;fill_triggers(obs_properties_get(props,"trigger"),w);return true;}
static bool source_modified(obs_properties_t*props,obs_property_t*,obs_data_t*s){auto*p=obs_properties_get(props,"method_filter");if(!p)return true;obs_property_list_clear(p);obs_source_t*src=obs_get_source_by_uuid(obs_data_get_string(s,"method_source"));if(src){obs_source_enum_filters(src,[](obs_source_t*,obs_source_t*f,void*d){obs_property_list_add_string(static_cast<obs_property_t*>(d),obs_source_get_name(f),obs_source_get_name(f));},p);obs_source_release(src);}return true;}
static void add_sources(obs_property_t*p){obs_enum_scenes([](void*d,obs_source_t*s){auto*p=static_cast<obs_property_t*>(d);obs_property_list_add_string(p,obs_source_get_name(s),obs_source_get_uuid(s));return true;},p);obs_enum_sources([](void*d,obs_source_t*s){auto*p=static_cast<obs_property_t*>(d);obs_property_list_add_string(p,obs_source_get_name(s),obs_source_get_uuid(s));return true;},p);}
static void add_methods(obs_property_t*p){obs_property_list_add_int(p,"None",WORKFLOW_TRIGGER_NONE);obs_property_list_add_int(p,"Frontend Action",WORKFLOW_TRIGGER_FRONTEND_ACTION);obs_property_list_add_int(p,"Source Visibility",WORKFLOW_TRIGGER_SOURCE_VISIBILITY);obs_property_list_add_int(p,"Source Mute",WORKFLOW_TRIGGER_SOURCE_MUTE);obs_property_list_add_int(p,"Source Audio Track",WORKFLOW_TRIGGER_SOURCE_AUDIO_TRACK);obs_property_list_add_int(p,"Source Hotkey",WORKFLOW_TRIGGER_SOURCE_HOTKEY);obs_property_list_add_int(p,"Filter Enable",WORKFLOW_TRIGGER_FILTER_ENABLE);obs_property_list_add_int(p,"Frontend Hotkey",WORKFLOW_TRIGGER_FRONTEND_HOTKEY);obs_property_list_add_int(p,"Setting",WORKFLOW_TRIGGER_SETTING);obs_property_list_add_int(p,"UDP Packet",WORKFLOW_TRIGGER_UDP_PACKET);obs_property_list_add_int(p,"WebSocket Request",WORKFLOW_TRIGGER_WEBSOCKET_REQUEST);obs_property_list_add_int(p,"WebSocket Event",WORKFLOW_TRIGGER_WEBSOCKET_EVENT);obs_property_list_add_int(p,"Scene Change",WORKFLOW_TRIGGER_SCENE_CHANGE);}
static void add_state(obs_properties_t*props){auto*p=obs_properties_add_list(props,"method_state","State",OBS_COMBO_TYPE_LIST,OBS_COMBO_FORMAT_INT);obs_property_list_add_int(p,"Enabled",WORKFLOW_TRIGGER_STATE_ENABLED);obs_property_list_add_int(p,"Disabled",WORKFLOW_TRIGGER_STATE_DISABLED);}
static bool method_modified(obs_properties_t*props,obs_property_t*,obs_data_t*s){const auto t=(workflow_trigger_type_t)obs_data_get_int(s,"method");const bool source=t>=WORKFLOW_TRIGGER_SOURCE_VISIBILITY&&t<=WORKFLOW_TRIGGER_SETTING;const bool state=t==WORKFLOW_TRIGGER_SOURCE_VISIBILITY||t==WORKFLOW_TRIGGER_SOURCE_MUTE||t==WORKFLOW_TRIGGER_SOURCE_AUDIO_TRACK||t==WORKFLOW_TRIGGER_FILTER_ENABLE;const bool text=t==WORKFLOW_TRIGGER_FRONTEND_ACTION||t==WORKFLOW_TRIGGER_FRONTEND_HOTKEY||t==WORKFLOW_TRIGGER_SOURCE_HOTKEY||t==WORKFLOW_TRIGGER_UDP_PACKET||t==WORKFLOW_TRIGGER_WEBSOCKET_REQUEST||t==WORKFLOW_TRIGGER_WEBSOCKET_EVENT;const bool setting=t==WORKFLOW_TRIGGER_SETTING;if(source&&!obs_properties_get(props,"method_source")){auto*p=obs_properties_add_list(props,"method_source","Source",OBS_COMBO_TYPE_LIST,OBS_COMBO_FORMAT_STRING);add_sources(p);obs_property_set_modified_callback(p,source_modified);}if(!source){obs_properties_remove_by_name(props,"method_source");obs_properties_remove_by_name(props,"method_filter");}if(t==WORKFLOW_TRIGGER_FILTER_ENABLE&&!obs_properties_get(props,"method_filter")){auto*p=obs_properties_add_list(props,"method_filter","Filter",OBS_COMBO_TYPE_LIST,OBS_COMBO_FORMAT_STRING);obs_property_set_modified_callback(obs_properties_get(props,"method_source"),source_modified);source_modified(props,nullptr,s);(void)p;}if(t!=WORKFLOW_TRIGGER_FILTER_ENABLE)obs_properties_remove_by_name(props,"method_filter");if(text&&!obs_properties_get(props,"method_text"))obs_properties_add_text(props,"method_text","Value",OBS_TEXT_DEFAULT);if(!text)obs_properties_remove_by_name(props,"method_text");if(setting){if(!obs_properties_get(props,"method_setting"))obs_properties_add_text(props,"method_setting","Setting",OBS_TEXT_DEFAULT);if(!obs_properties_get(props,"method_value"))obs_properties_add_text(props,"method_value","Expected Value",OBS_TEXT_DEFAULT);}else{obs_properties_remove_by_name(props,"method_setting");obs_properties_remove_by_name(props,"method_value");}if(state&&!obs_properties_get(props,"method_state"))add_state(props);if(!state)obs_properties_remove_by_name(props,"method_state");return true;}
}
obs_properties_t*workflow_trigger_filter_properties(void*){auto*props=obs_properties_create();auto*workflow=obs_properties_add_list(props,"workflow","Workflow",OBS_COMBO_TYPE_LIST,OBS_COMBO_FORMAT_STRING);auto*trigger=obs_properties_add_list(props,"trigger","Trigger Node",OBS_COMBO_TYPE_LIST,OBS_COMBO_FORMAT_STRING);obs_property_list_add_string(trigger,"Select a workflow first","");obs_property_set_modified_callback(workflow,workflow_modified);if(auto*m=workflow_persistence_manager())for(size_t i=0;i<m->workflow_count;++i)obs_property_list_add_string(workflow,m->workflows[i].name,m->workflows[i].id);auto*method=obs_properties_add_list(props,"method","Additional Trigger",OBS_COMBO_TYPE_LIST,OBS_COMBO_FORMAT_INT);add_methods(method);obs_property_set_modified_callback(method,method_modified);return props;}
