#include "workflow-node.h"
#include "workflow-node-timing-defaults.h"
#include "workflow-trigger-filter-instance.h"
#include "workflow-persistence.h"
#include <obs.h>
#include <QGraphicsTextItem>
#include <QPainter>
#include <QPen>
#include <QString>
#include <QStringList>
#include <utility>
namespace{static QString text(const char*v){return v?QString::fromUtf8(v):QString();}}
NodeItem::NodeItem(EditorNode n,QGraphicsItem*p):QGraphicsRectItem(p),node_(std::move(n)){setRect(0,0,nodeWidth,minimumHeight);setFlag(QGraphicsItem::ItemIsMovable);setFlag(QGraphicsItem::ItemIsSelectable);setFlag(QGraphicsItem::ItemSendsGeometryChanges);setPos(node_.position);refreshStyle();title_=new QGraphicsTextItem(text(node_.workflow.name),this);title_->setDefaultTextColor(Qt::white);title_->setTextWidth(nodeWidth-28);title_->setPos(14,10);type_=new QGraphicsTextItem(this);type_->setDefaultTextColor(QColor(175,185,200));type_->setPos(14,34);details_=new QGraphicsTextItem(this);details_->setDefaultTextColor(QColor(210,215,220));details_->setTextWidth(nodeWidth-28);details_->setPos(14,56);refreshDisplay();}
QString NodeItem::id()const{return text(node_.workflow.id);}QString NodeItem::nodeName()const{return text(node_.workflow.name);}workflow_node_t*NodeItem::workflowNode(){return &node_.workflow;}const workflow_node_t*NodeItem::workflowNode()const{return &node_.workflow;}
void NodeItem::refreshDisplay(){if(!title_||!type_||!details_)return;title_->setPlainText(text(node_.workflow.name));type_->setPlainText(node_.workflow.type==WORKFLOW_NODE_TRIGGER?"TRIGGER":"ACTION");if(node_.workflow.type==WORKFLOW_NODE_TRIGGER){QStringList refs;for(size_t i=0;i<node_.workflow.trigger_count;++i){auto*f=workflow_trigger_filter_find(node_.workflow.triggers[i].source_uuid,node_.workflow.triggers[i].filter_uuid);auto*s=obs_get_source_by_uuid(node_.workflow.triggers[i].source_uuid);if(f&&s)refs<<QString("%1 / %2").arg(text(obs_source_get_name(s)),text(obs_source_get_name(f)));if(f)obs_source_release(f);if(s)obs_source_release(s);}details_->setPlainText(refs.isEmpty()?"No Workflow Trigger Filters selected":refs.join("\n"));}else{const QString source=text(node_.workflow.action.scene_name),filter=text(node_.workflow.action.filter_name);uint64_t sd=node_.workflow.start_delay.delay_ms,d=node_.workflow.duration.duration_ms,ed=node_.workflow.end_delay.delay_ms;const auto defaults=workflow_node_read_timing_defaults(node_.workflow.action.scene_name,node_.workflow.action.filter_name);if(defaults.valid){if(node_.workflow.start_delay.mode==WORKFLOW_USE_EXISTING)sd=defaults.start_delay_ms;if(node_.workflow.duration.mode==WORKFLOW_USE_EXISTING)d=defaults.duration_ms;if(node_.workflow.end_delay.mode==WORKFLOW_USE_EXISTING)ed=defaults.end_delay_ms;}details_->setPlainText(QString("%1\n%2\nDelay %3 ms   Duration %4 ms   End %5 ms\nSimultaneous %6   End %7   Next %8").arg(source.isEmpty()?"No source selected":source,filter.isEmpty()?"No Move filter selected":filter).arg((qulonglong)sd).arg((qulonglong)d).arg((qulonglong)ed).arg((qulonglong)node_.workflow.simultaneous_node_count).arg((qulonglong)node_.workflow.end_node_count).arg((qulonglong)node_.workflow.next_node_count));}updateGeometryForText();update();}
bool NodeItem::isOnConnectionHandle(const QPointF&p)const{const QPointF l=mapFromScene(p);return QRectF(rect().left(),rect().bottom()-dragBarHitHeight,rect().width(),dragBarHitHeight).contains(l);}QVariant NodeItem::itemChange(GraphicsItemChange c,const QVariant&v){if(c==ItemPositionHasChanged)node_.position=v.toPointF();return QGraphicsRectItem::itemChange(c,v);}void NodeItem::paint(QPainter*p,const QStyleOptionGraphicsItem*o,QWidget*w){QGraphicsRectItem::paint(p,o,w);const QRectF r(rect().left(),rect().bottom()-dragBarHeight,rect().width(),dragBarHeight);p->setPen(Qt::NoPen);p->setBrush(QColor(235,145,45));p->drawRect(r);}void NodeItem::updateGeometryForText(){const qreal h=qMax(minimumHeight,56.0+details_->boundingRect().height()+14.0);if(!qFuzzyCompare(rect().height(),h)){prepareGeometryChange();setRect(0,0,nodeWidth,h);}}void NodeItem::refreshStyle(){if(node_.workflow.type==WORKFLOW_NODE_TRIGGER){setBrush(QColor(35,70,85));setPen(QPen(QColor(70,180,220),2));}else{setBrush(QColor(42,45,50));setPen(QPen(QColor(110,120,135),1));}}