#include "workflow-persistence-json.h"
#include <QJsonArray>
#include <cstring>
namespace {
void text(char *dst,size_t n,const QString &v){const QByteArray b=v.toUtf8();std::strncpy(dst,b.constData(),n-1);dst[n-1]='\0';}
QJsonArray ids(size_t c,const char a[][WORKFLOW_MAX_NAME]){QJsonArray r;for(size_t i=0;i<c;++i)r.append(QString::fromUtf8(a[i]));return r;}
void read_ids(QJsonArray a,size_t &c,char out[][WORKFLOW_MAX_NAME]){c=0;for(const auto &v:a){if(c>=WORKFLOW_MAX_LINKS||!v.isString())break;text(out[c++],WORKFLOW_MAX_NAME,v.toString());}}
QJsonObject trigger(const workflow_trigger_ref_t&t){return QJsonObject{{"type",(int)t.type},{"state",(int)t.state},{"audio_track",t.audio_track},{"udp_port",(int)t.udp_port},{"action",t.action},{"scene",t.scene_name},{"filter",t.filter_name},{"filter_id",t.filter_id},{"hotkey",t.hotkey},{"setting",t.setting_name},{"target_workflow",t.target_workflow_id},{"value",t.value},{"match",t.match}};}
void read_trigger(const QJsonObject&o,workflow_trigger_ref_t&t){t.type=(workflow_trigger_type_t)o["type"].toInt();t.state=(workflow_trigger_state_t)o["state"].toInt(1);t.audio_track=o["audio_track"].toInt();t.udp_port=(uint16_t)o["udp_port"].toInt();text(t.action,WORKFLOW_MAX_NAME,o["action"].toString());text(t.scene_name,WORKFLOW_MAX_NAME,o["scene"].toString());text(t.filter_name,WORKFLOW_MAX_NAME,o["filter"].toString());text(t.filter_id,WORKFLOW_MAX_NAME,o["filter_id"].toString());text(t.hotkey,WORKFLOW_MAX_NAME,o["hotkey"].toString());text(t.setting_name,WORKFLOW_MAX_NAME,o["setting"].toString());text(t.target_workflow_id,WORKFLOW_MAX_NAME,o["target_workflow"].toString());text(t.value,WORKFLOW_MAX_VALUE,o["value"].toString());text(t.match,WORKFLOW_MAX_VALUE,o["match"].toString());}
QJsonObject node(const workflow_node_t&n){QJsonObject a{{"scene",QString::fromUtf8(n.action.scene_name)},{"source",QString::fromUtf8(n.action.source_name)},{"filter",QString::fromUtf8(n.action.filter_name)},{"filter_id",QString::fromUtf8(n.action.filter_id)},{"kind",(int)n.action.kind},{"scene_completion",(int)n.action.scene_completion}};return QJsonObject{{"id",n.id},{"name",n.name},{"type",(int)n.type},{"x",n.position_x},{"y",n.position_y},{"trigger",trigger(n.trigger)},{"duration_mode",(int)n.duration.mode},{"duration_ms",(qint64)n.duration.duration_ms},{"start_mode",(int)n.start_delay.mode},{"start_ms",(qint64)n.start_delay.delay_ms},{"end_mode",(int)n.end_delay.mode},{"end_ms",(qint64)n.end_delay.delay_ms},{"sim_mode",(int)n.simultaneous_actions_mode},{"end_actions_mode",(int)n.end_actions_mode},{"next_mode",(int)n.next_actions_mode},{"start_trigger_mode",(int)n.start_trigger_mode},{"stop_trigger_mode",(int)n.stop_trigger_mode},{"next_move_mode",(int)n.next_move_on_mode},{"start_value",n.start_trigger_value},{"stop_value",n.stop_trigger_value},{"next_value",n.next_move_on_value},{"end",ids(n.end_node_count,n.end_node_ids)},{"simultaneous",ids(n.simultaneous_node_count,n.simultaneous_node_ids)},{"next",ids(n.next_node_count,n.next_node_ids)},{"shortcut",ids(n.shortcut_node_count,n.shortcut_node_ids)},{"action",a}};}
void read_node(const QJsonObject&o,workflow_node_t&n){std::memset(&n,0,sizeof(n));text(n.id,WORKFLOW_MAX_NAME,o["id"].toString());text(n.name,WORKFLOW_MAX_NAME,o["name"].toString());n.type=(workflow_node_type_t)o["type"].toInt();n.position_x=o["x"].toInt();n.position_y=o["y"].toInt();read_trigger(o["trigger"].toObject(),n.trigger);const auto a=o["action"].toObject();text(n.action.scene_name,WORKFLOW_MAX_NAME,a["scene"].toString());text(n.action.source_name,WORKFLOW_MAX_NAME,a["source"].toString());text(n.action.filter_name,WORKFLOW_MAX_NAME,a["filter"].toString());text(n.action.filter_id,WORKFLOW_MAX_NAME,a["filter_id"].toString());n.action.kind=(workflow_move_kind_t)a["kind"].toInt();n.action.scene_completion=(workflow_scene_completion_t)a["scene_completion"].toInt();n.duration.mode=(workflow_value_mode_t)o["duration_mode"].toInt();n.duration.duration_ms=(uint64_t)o["duration_ms"].toInteger();n.start_delay.mode=(workflow_value_mode_t)o["start_mode"].toInt();n.start_delay.delay_ms=(uint64_t)o["start_ms"].toInteger();n.end_delay.mode=(workflow_value_mode_t)o["end_mode"].toInt();n.end_delay.delay_ms=(uint64_t)o["end_ms"].toInteger();n.simultaneous_actions_mode=(workflow_value_mode_t)o["sim_mode"].toInt();n.end_actions_mode=(workflow_value_mode_t)o["end_actions_mode"].toInt();n.next_actions_mode=(workflow_value_mode_t)o["next_mode"].toInt();n.start_trigger_mode=(workflow_value_mode_t)o["start_trigger_mode"].toInt();n.stop_trigger_mode=(workflow_value_mode_t)o["stop_trigger_mode"].toInt();n.next_move_on_mode=(workflow_value_mode_t)o["next_move_mode"].toInt();text(n.start_trigger_value,WORKFLOW_MAX_VALUE,o["start_value"].toString());text(n.stop_trigger_value,WORKFLOW_MAX_VALUE,o["stop_value"].toString());text(n.next_move_on_value,WORKFLOW_MAX_VALUE,o["next_value"].toString());read_ids(o["end"].toArray(),n.end_node_count,n.end_node_ids);read_ids(o["simultaneous"].toArray(),n.simultaneous_node_count,n.simultaneous_node_ids);read_ids(o["next"].toArray(),n.next_node_count,n.next_node_ids);read_ids(o["shortcut"].toArray(),n.shortcut_node_count,n.shortcut_node_ids);}
}
QJsonObject workflow_manager_to_json(const workflow_manager_t*m){QJsonArray ws;for(size_t i=0;i<m->workflow_count;++i){const auto&w=m->workflows[i];QJsonArray ns;for(size_t j=0;j<w.node_count;++j)ns.append(node(w.nodes[j]));ws.append(QJsonObject{{"id",w.id},{"name",w.name},{"enabled",w.enabled},{"entry",ids(w.entry_node_count,w.entry_node_ids)},{"nodes",ns}});}return QJsonObject{{"version",1},{"selected",m->selected_workflow_id},{"workflows",ws}};}
bool workflow_manager_from_json(workflow_manager_t*m,const QJsonObject&o){const auto ws=o["workflows"].toArray();if(ws.isEmpty())return false;std::memset(m,0,sizeof(*m));text(m->selected_workflow_id,WORKFLOW_MAX_NAME,o["selected"].toString());for(const auto&v:ws){if(m->workflow_count>=WORKFLOW_MANAGER_MAX_WORKFLOWS)break;const auto w=v.toObject();auto&dst=m->workflows[m->workflow_count++];text(dst.id,WORKFLOW_MAX_NAME,w["id"].toString());text(dst.name,WORKFLOW_MAX_NAME,w["name"].toString());dst.enabled=w["enabled"].toBool(true);read_ids(w["entry"].toArray(),dst.entry_node_count,dst.entry_node_ids);for(const auto&nv:w["nodes"].toArray()){if(dst.node_count>=WORKFLOW_MAX_NODES)break;read_node(nv.toObject(),dst.nodes[dst.node_count++]);}}if(!workflow_manager_selected_const(m)&&m->workflow_count)text(m->selected_workflow_id,WORKFLOW_MAX_NAME,m->workflows[0].id);return m->workflow_count>0;}
